# Generated by Django 4.0.6 on 2022-10-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problem_solver'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
