# Generated by Django 4.0.6 on 2022-10-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
