# Generated by Django 4.0.6 on 2022-07-26 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='author',
            new_name='sender',
        ),
    ]
