# Generated by Django 4.0.6 on 2022-12-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('adjRatio', models.FloatField()),
                ('buyCount', models.IntegerField()),
                ('buyForeignQuantity', models.IntegerField()),
                ('buyForeignValue', models.IntegerField()),
                ('buyQuantity', models.IntegerField()),
                ('currentForeignRoom', models.IntegerField()),
                ('date', models.CharField(max_length=30)),
                ('dealVolume', models.IntegerField()),
                ('priceAverage', models.FloatField()),
                ('priceBasic', models.FloatField()),
                ('priceClose', models.FloatField()),
                ('priceHigh', models.FloatField()),
                ('priceLow', models.FloatField()),
                ('priceOpen', models.FloatField()),
                ('propTradingNetDealValue', models.IntegerField()),
                ('propTradingNetPTValue', models.IntegerField()),
                ('propTradingNetValue', models.IntegerField()),
                ('putthroughValue', models.IntegerField()),
                ('putthroughVolume', models.IntegerField()),
                ('sellCount', models.IntegerField()),
                ('sellForeignQuantity', models.IntegerField()),
                ('sellForeignValue', models.IntegerField()),
                ('sellQuantity', models.IntegerField()),
                ('symbol', models.CharField(max_length=10)),
                ('totalValue', models.IntegerField()),
                ('totalVolume', models.IntegerField()),
            ],
        ),
    ]
