# Generated by Django 4.0.6 on 2022-12-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='buyCount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='buyForeignQuantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='buyForeignValue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='buyQuantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='currentForeignRoom',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dealVolume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='propTradingNetDealValue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='propTradingNetPTValue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='propTradingNetValue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='putthroughValue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='putthroughVolume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sellCount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sellForeignQuantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sellForeignValue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sellQuantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='totalValue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='totalVolume',
            field=models.FloatField(),
        ),
    ]
